version: '3.7'

services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
    - 34101:16686/tcp
    volumes:
    - jaeger-volume:/tmp:rw

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_pass
      RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq_user
    ports:
    - 34102:15672/tcp
    secrets:
    - source: rabbitmq_pass
    - source: rabbitmq_user
    volumes:
    - rabbitmq-volume:/var/lib/rabbitmq:rw
 
  service:
    image: eassbhhtgu/randomwebbrowsing:latest
    environment:
    - DOTNET_ENVIRONMENT=Production
    depends_on:
    - jaeger
    - rabbitmq
    secrets:
    - source: rabbitmq_pass
    - source: rabbitmq_user

secrets:
  rabbitmq_pass:
    external: true
    name: randomwebbrowsing_rabbitmq_pass
  rabbitmq_user:
    external: true
    name: randomwebbrowsing_rabbitmq_user

volumes:
  jaeger-volume: {}
  rabbitmq-volume: {}
